alter table public.profiles
add column if not exists friend_code text;

update public.profiles
set friend_code = upper(substr(md5(user_id::text || random()::text), 1, 10))
where friend_code is null;

alter table public.profiles
alter column friend_code set default upper(substr(encode(extensions.gen_random_bytes(8), 'hex'), 1, 10));

alter table public.profiles
alter column friend_code set not null;

create unique index if not exists profiles_friend_code_key
on public.profiles (upper(friend_code));

create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references auth.users(id) on delete cascade,
  addressee_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending'
    check (status in ('pending', 'accepted', 'rejected')),
  created_at timestamptz not null default timezone('utc', now()),
  responded_at timestamptz,
  pair_low uuid generated always as (least(requester_id, addressee_id)) stored,
  pair_high uuid generated always as (greatest(requester_id, addressee_id)) stored,
  constraint friendships_not_self check (requester_id <> addressee_id),
  constraint friendships_unique_pair unique (pair_low, pair_high)
);

create index if not exists friendships_requester_id_idx
on public.friendships (requester_id);

create index if not exists friendships_addressee_id_idx
on public.friendships (addressee_id);

alter table public.friendships enable row level security;

revoke all on table public.friendships from public, anon, authenticated;
revoke all on sequence public.friendships_id_seq from public, anon, authenticated;
grant all on table public.friendships to service_role;
grant all on sequence public.friendships_id_seq to service_role;

revoke select (friend_code) on table public.profiles from public, anon, authenticated;

create or replace function public.get_friend_dashboard()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'friendCode',
    (
      select p.friend_code
      from public.profiles p
      where p.user_id = auth.uid()
    ),
    'friends',
    coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'userId', friend_profile.user_id,
          'nickname', friend_profile.nickname
        )
        order by lower(friend_profile.nickname), friend_profile.user_id
      )
      from public.friendships f
      join public.profiles friend_profile
        on friend_profile.user_id = case
          when f.requester_id = auth.uid() then f.addressee_id
          else f.requester_id
        end
      where f.status = 'accepted'
        and auth.uid() in (f.requester_id, f.addressee_id)
    ), '[]'::jsonb),
    'incoming',
    coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'requestId', f.id,
          'userId', requester.user_id,
          'nickname', requester.nickname,
          'createdAt', f.created_at
        )
        order by f.created_at desc
      )
      from public.friendships f
      join public.profiles requester on requester.user_id = f.requester_id
      where f.addressee_id = auth.uid()
        and f.status = 'pending'
    ), '[]'::jsonb),
    'outgoing',
    coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'requestId', f.id,
          'userId', addressee.user_id,
          'nickname', addressee.nickname,
          'createdAt', f.created_at
        )
        order by f.created_at desc
      )
      from public.friendships f
      join public.profiles addressee on addressee.user_id = f.addressee_id
      where f.requester_id = auth.uid()
        and f.status = 'pending'
    ), '[]'::jsonb)
  );
$$;

create or replace function public.send_friend_request_by_code(p_friend_code text)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_user_id uuid;
  existing_friendship public.friendships%rowtype;
  friendship_id bigint;
begin
  if auth.uid() is null then
    raise exception 'Authentication required.';
  end if;

  select p.user_id
  into target_user_id
  from public.profiles p
  where upper(p.friend_code) = upper(trim(p_friend_code))
  limit 1;

  if target_user_id is null then
    raise exception 'Friend code not found.';
  end if;
  if target_user_id = auth.uid() then
    raise exception 'You cannot add yourself.';
  end if;

  select f.*
  into existing_friendship
  from public.friendships f
  where f.pair_low = least(auth.uid(), target_user_id)
    and f.pair_high = greatest(auth.uid(), target_user_id);

  if existing_friendship.id is not null and existing_friendship.status = 'accepted' then
    raise exception 'Already friends.';
  end if;
  if existing_friendship.id is not null and existing_friendship.status = 'pending' then
    raise exception 'Friend request already exists.';
  end if;

  if existing_friendship.id is not null then
    update public.friendships
    set requester_id = auth.uid(),
        addressee_id = target_user_id,
        status = 'pending',
        created_at = timezone('utc', now()),
        responded_at = null
    where id = existing_friendship.id
    returning id into friendship_id;
  else
    insert into public.friendships (requester_id, addressee_id)
    values (auth.uid(), target_user_id)
    returning id into friendship_id;
  end if;

  return friendship_id;
end;
$$;

create or replace function public.respond_friend_request(
  p_request_id bigint,
  p_accept boolean
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.friendships
  set status = case when p_accept then 'accepted' else 'rejected' end,
      responded_at = timezone('utc', now())
  where id = p_request_id
    and addressee_id = auth.uid()
    and status = 'pending';

  if not found then
    raise exception 'Pending friend request not found.';
  end if;
end;
$$;

create or replace function public.remove_friend(p_friend_user_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.friendships
  where status = 'accepted'
    and pair_low = least(auth.uid(), p_friend_user_id)
    and pair_high = greatest(auth.uid(), p_friend_user_id);

  if not found then
    raise exception 'Friendship not found.';
  end if;
end;
$$;

create or replace function public.invite_friends_to_settlement(
  p_settlement_id bigint,
  p_friend_ids uuid[]
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  requested_count integer;
  accepted_count integer;
  inserted_count integer;
begin
  if not public.is_settlement_owner(p_settlement_id) then
    raise exception 'Only the settlement owner can invite friends.';
  end if;

  select count(distinct requested_id)
  into requested_count
  from unnest(coalesce(p_friend_ids, '{}'::uuid[])) requested_id
  where requested_id is not null
    and requested_id <> auth.uid();

  if requested_count = 0 then
    return 0;
  end if;

  select count(distinct requested_id)
  into accepted_count
  from unnest(p_friend_ids) requested_id
  where exists (
    select 1
    from public.friendships f
    where f.status = 'accepted'
      and f.pair_low = least(auth.uid(), requested_id)
      and f.pair_high = greatest(auth.uid(), requested_id)
  );

  if accepted_count <> requested_count then
    raise exception 'Every invited account must be an accepted friend.';
  end if;

  insert into public.settlement_members (settlement_id, user_id)
  select p_settlement_id, requested_id
  from (
    select distinct unnest(p_friend_ids) as requested_id
  ) requested
  where requested_id is not null
    and requested_id <> auth.uid()
  on conflict (settlement_id, user_id) do nothing;

  get diagnostics inserted_count = row_count;
  return inserted_count;
end;
$$;

revoke all on function public.get_friend_dashboard() from public, anon;
revoke all on function public.send_friend_request_by_code(text) from public, anon;
revoke all on function public.respond_friend_request(bigint, boolean) from public, anon;
revoke all on function public.remove_friend(uuid) from public, anon;
revoke all on function public.invite_friends_to_settlement(bigint, uuid[]) from public, anon;

grant execute on function public.get_friend_dashboard() to authenticated, service_role;
grant execute on function public.send_friend_request_by_code(text) to authenticated, service_role;
grant execute on function public.respond_friend_request(bigint, boolean) to authenticated, service_role;
grant execute on function public.remove_friend(uuid) to authenticated, service_role;
grant execute on function public.invite_friends_to_settlement(bigint, uuid[]) to authenticated, service_role;
