create extension if not exists pgcrypto with schema extensions;

create table public.settlements (
  id bigint generated always as identity primary key,
  created_at timestamptz default now(),
  title text not null,
  date date not null,
  participants jsonb not null,
  base_currency text not null,
  is_settled boolean default false,
  user_id uuid default auth.uid() references auth.users(id),
  invite_code text unique,
  deleted_at timestamptz
);

create table public.expenses (
  id bigint generated always as identity primary key,
  created_at timestamptz default now(),
  settlement_id bigint references public.settlements(id) on delete cascade,
  name text not null,
  original_amount numeric not null,
  currency text not null,
  amount numeric not null,
  payer text not null,
  split text not null,
  shares jsonb not null,
  expense_date timestamptz default now(),
  user_id uuid default auth.uid() references auth.users(id)
);

create table public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null,
  created_at timestamptz default timezone('utc', now()) not null,
  admin_pin text
);

create table public.settlement_members (
  id bigint generated by default as identity primary key,
  settlement_id bigint references public.settlements(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  email text,
  provider text,
  joined_at timestamptz default timezone('utc', now()) not null,
  last_read_at timestamptz default timezone('utc', now()),
  unique (settlement_id, user_id)
);

create table public.chat_messages (
  id uuid default gen_random_uuid() primary key,
  settlement_id bigint references public.settlements(id) on delete cascade,
  user_id uuid references public.profiles(user_id) on delete cascade,
  content text not null,
  created_at timestamptz default timezone('utc', now()) not null,
  is_edited boolean default false,
  is_deleted boolean default false,
  is_hidden_admin boolean default false
);

create index idx_expenses_settlement_id on public.expenses(settlement_id);
create index idx_expenses_user_id on public.expenses(user_id);
create index idx_settlement_members_settlement_id on public.settlement_members(settlement_id);
create index idx_settlement_members_user_id on public.settlement_members(user_id);
create index idx_chat_messages_settlement_id on public.chat_messages(settlement_id);

alter table public.settlements enable row level security;
alter table public.expenses enable row level security;
alter table public.profiles enable row level security;
alter table public.settlement_members enable row level security;
alter table public.chat_messages enable row level security;

revoke all on table public.settlements from anon, authenticated;
revoke all on table public.expenses from anon, authenticated;
revoke all on table public.profiles from anon, authenticated;
revoke all on table public.settlement_members from anon, authenticated;
revoke all on table public.chat_messages from anon, authenticated;

grant select, insert, update, delete on table public.settlements to authenticated;
grant select, insert, update, delete on table public.expenses to authenticated;
grant select, insert, update, delete on table public.settlement_members to authenticated;
grant select, insert, update on table public.chat_messages to authenticated;

grant select (user_id, nickname, created_at) on table public.profiles to anon;
grant select (user_id, nickname, created_at) on table public.profiles to authenticated;
grant insert (user_id, nickname) on table public.profiles to authenticated;
grant update (nickname) on table public.profiles to authenticated;

grant usage, select on sequence public.settlements_id_seq to authenticated;
grant usage, select on sequence public.expenses_id_seq to authenticated;
grant usage, select on sequence public.settlement_members_id_seq to authenticated;

grant all on table public.settlements to service_role;
grant all on table public.expenses to service_role;
grant all on table public.profiles to service_role;
grant all on table public.settlement_members to service_role;
grant all on table public.chat_messages to service_role;
grant all on sequence public.settlements_id_seq to service_role;
grant all on sequence public.expenses_id_seq to service_role;
grant all on sequence public.settlement_members_id_seq to service_role;

create or replace function public.is_settlement_owner(p_settlement_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.settlements s
    where s.id = p_settlement_id
      and s.user_id = auth.uid()
      and s.deleted_at is null
  );
$$;

create or replace function public.is_settlement_member(p_settlement_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.settlement_members sm
    join public.settlements s on s.id = sm.settlement_id
    where sm.settlement_id = p_settlement_id
      and sm.user_id = auth.uid()
      and s.deleted_at is null
  );
$$;

create or replace function public.can_access_settlement(p_settlement_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select
    public.is_settlement_owner(p_settlement_id)
    or public.is_settlement_member(p_settlement_id);
$$;

revoke all on function public.is_settlement_owner(bigint) from public, anon;
revoke all on function public.is_settlement_member(bigint) from public, anon;
revoke all on function public.can_access_settlement(bigint) from public, anon;
grant execute on function public.is_settlement_owner(bigint) to authenticated, service_role;
grant execute on function public.is_settlement_member(bigint) to authenticated, service_role;
grant execute on function public.can_access_settlement(bigint) to authenticated, service_role;

create policy "Profiles are publicly readable"
on public.profiles
for select
to anon, authenticated
using (true);

create policy "Users can insert their own profile"
on public.profiles
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update their own profile"
on public.profiles
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Owners and members can view settlements"
on public.settlements
for select
to authenticated
using (public.can_access_settlement(id));

create policy "Authenticated users can create their own settlements"
on public.settlements
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Owners can update settlements"
on public.settlements
for update
to authenticated
using (public.is_settlement_owner(id))
with check (auth.uid() = user_id);

create policy "Owners can delete settlements"
on public.settlements
for delete
to authenticated
using (public.is_settlement_owner(id));

create policy "Owners and members can view expenses"
on public.expenses
for select
to authenticated
using (public.can_access_settlement(settlement_id));

create policy "Owners and members can create expenses"
on public.expenses
for insert
to authenticated
with check (
  auth.uid() = user_id
  and public.can_access_settlement(settlement_id)
);

create policy "Owners and members can update expenses"
on public.expenses
for update
to authenticated
using (public.can_access_settlement(settlement_id))
with check (public.can_access_settlement(settlement_id));

create policy "Owners and members can delete expenses"
on public.expenses
for delete
to authenticated
using (public.can_access_settlement(settlement_id));

create policy "Room participants can view member rows"
on public.settlement_members
for select
to authenticated
using (public.can_access_settlement(settlement_id));

create policy "Users can add their own member row"
on public.settlement_members
for insert
to authenticated
with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.settlements s
    where s.id = settlement_id
      and s.deleted_at is null
  )
);

create policy "Members can update their own member row"
on public.settlement_members
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Owners can remove members and members can leave"
on public.settlement_members
for delete
to authenticated
using (
  auth.uid() = user_id
  or public.is_settlement_owner(settlement_id)
);

create policy "Room participants can view messages"
on public.chat_messages
for select
to authenticated
using (public.can_access_settlement(settlement_id));

create policy "Room participants can create their own messages"
on public.chat_messages
for insert
to authenticated
with check (
  auth.uid() = user_id
  and public.can_access_settlement(settlement_id)
);

create policy "Authors and administrators can update messages"
on public.chat_messages
for update
to authenticated
using (
  auth.uid() = user_id
  or auth.jwt() ->> 'email' = 'eowert72@gmail.com'
)
with check (
  auth.uid() = user_id
  or auth.jwt() ->> 'email' = 'eowert72@gmail.com'
);

create or replace function public.get_public_settlement_by_invite_code(p_invite_code text)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  normalized_code text := upper(trim(coalesce(p_invite_code, '')));
  preview jsonb;
begin
  if normalized_code !~ '^[A-Z0-9]{6}$' then
    return null;
  end if;

  select jsonb_build_object(
    'id', s.id,
    'date', s.date,
    'title', s.title,
    'expenses', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', e.id,
          'name', e.name,
          'payer', e.payer,
          'split', e.split,
          'amount', e.amount,
          'shares', e.shares,
          'currency', e.currency,
          'created_at', e.created_at,
          'expense_date', e.expense_date,
          'settlement_id', e.settlement_id,
          'original_amount', e.original_amount
        )
        order by e.expense_date desc, e.created_at desc
      )
      from public.expenses e
      where e.settlement_id = s.id
    ), '[]'::jsonb),
    'created_at', s.created_at,
    'is_settled', s.is_settled,
    'invite_code', s.invite_code,
    'participants', s.participants,
    'base_currency', s.base_currency
  )
  into preview
  from public.settlements s
  where upper(s.invite_code) = normalized_code
    and s.deleted_at is null;

  return preview;
end;
$$;

create or replace function public.get_settlement_id_by_invite_code(p_invite_code text)
returns bigint
language sql
stable
security definer
set search_path = ''
as $$
  select s.id
  from public.settlements s
  where upper(s.invite_code) = upper(trim(coalesce(p_invite_code, '')))
    and s.deleted_at is null
  limit 1;
$$;

create or replace function public.join_settlement_by_invite_code(p_invite_code text)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_uid uuid := auth.uid();
  target_settlement_id bigint;
  jwt jsonb := auth.jwt();
begin
  if current_uid is null then
    raise exception 'Authentication required.';
  end if;

  select s.id
  into target_settlement_id
  from public.settlements s
  where upper(s.invite_code) = upper(trim(coalesce(p_invite_code, '')))
    and s.deleted_at is null
  limit 1;

  if target_settlement_id is null then
    return null;
  end if;

  insert into public.settlement_members (
    settlement_id,
    user_id,
    email,
    provider
  )
  values (
    target_settlement_id,
    current_uid,
    jwt ->> 'email',
    coalesce(jwt -> 'app_metadata' ->> 'provider', 'email')
  )
  on conflict (settlement_id, user_id)
  do update set
    email = excluded.email,
    provider = excluded.provider;

  return target_settlement_id;
end;
$$;

create or replace function public.get_my_admin_pin()
returns text
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  current_uid uuid := auth.uid();
  pin text;
begin
  if current_uid is null then
    raise exception 'Authentication required.';
  end if;

  select p.admin_pin
  into pin
  from public.profiles p
  where p.user_id = current_uid;

  return pin;
end;
$$;

create or replace function public.set_my_admin_pin(p_admin_pin text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_uid uuid := auth.uid();
begin
  if current_uid is null then
    raise exception 'Authentication required.';
  end if;

  if p_admin_pin is not null and length(p_admin_pin) > 32 then
    raise exception 'PIN is too long.';
  end if;

  update public.profiles
  set admin_pin = nullif(trim(p_admin_pin), '')
  where user_id = current_uid;

  if not found then
    raise exception 'Profile not found.';
  end if;
end;
$$;

create or replace function public.kick_member(
  p_settlement_id bigint,
  p_target_uid uuid
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required.';
  end if;

  if not public.is_settlement_owner(p_settlement_id) then
    raise exception 'Only the settlement owner can remove members.';
  end if;

  if exists (
    select 1
    from public.settlements s
    where s.id = p_settlement_id
      and s.user_id = p_target_uid
  ) then
    raise exception 'The settlement owner cannot be removed.';
  end if;

  delete from public.settlement_members
  where settlement_id = p_settlement_id
    and user_id = p_target_uid;
end;
$$;

create or replace function public.delete_user()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_uid uuid := auth.uid();
begin
  if current_uid is null then
    raise exception 'Authentication required.';
  end if;

  update public.settlements
  set user_id = null
  where user_id = current_uid;

  update public.expenses
  set user_id = null
  where user_id = current_uid;

  delete from auth.users
  where id = current_uid;
end;
$$;

revoke all on function public.get_public_settlement_by_invite_code(text) from public;
revoke all on function public.get_settlement_id_by_invite_code(text) from public, anon;
revoke all on function public.join_settlement_by_invite_code(text) from public, anon;
revoke all on function public.get_my_admin_pin() from public, anon;
revoke all on function public.set_my_admin_pin(text) from public, anon;
revoke all on function public.kick_member(bigint, uuid) from public, anon;
revoke all on function public.delete_user() from public, anon;

grant execute on function public.get_public_settlement_by_invite_code(text)
  to anon, authenticated, service_role;
grant execute on function public.get_settlement_id_by_invite_code(text)
  to authenticated, service_role;
grant execute on function public.join_settlement_by_invite_code(text)
  to authenticated, service_role;
grant execute on function public.get_my_admin_pin()
  to authenticated, service_role;
grant execute on function public.set_my_admin_pin(text)
  to authenticated, service_role;
grant execute on function public.kick_member(bigint, uuid)
  to authenticated, service_role;
grant execute on function public.delete_user()
  to authenticated, service_role;

alter publication supabase_realtime add table public.chat_messages;
alter publication supabase_realtime add table public.settlement_members;
